apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: couchdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
      - name: couchdb
        image: couchdb
        ports:
        - containerPort: 5984
        volumeMounts:
        - mountPath: /usr/local/var/lib/couchdb
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: couchdb-pvc
        
