apiVersion: batch/v1
kind: Job
metadata:
  name: couchdb-dataloader
spec:
  template:
    metadata:
      labels:
        app: couchdb-dataloader
    spec:
      containers:
      - name: couchdb-dataloader
        image: gpii/preferences-server-data-loader
        env:
        - name: COUCHDB_HOST_ADDRESS
          value: couchdb.default.svc.cluster.local:5984
        - name: CLEAR_INDEX
          value: 'true'
      restartPolicy: OnFailure