apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: flow-manager
spec:
  replicas: 6
  template:
    metadata:
      labels:
        app: flow-manager
    spec:
      containers:
      - name: flow-manager
        image: gpii/flow-manager
        ports:
        - containerPort: 8081
        env:
        - name: PREFERENCES_SERVER_HOST_ADDRESS
          value: preferences.default.svc.cluster.local
        - name: NODE_ENV
          value: gpii.config.cloudBased.production
