apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: flow-manager
spec:
  replicas: 6
  template:
    metadata:
      labels:
        app: flow-manager
    spec:
      containers:
      - name: flow-manager
        image: gpii/universal
        ports:
        - containerPort: 8081
        env:
        - name: NODE_ENV
          value: gpii.config.cloudBased.flowManager.production
        - name: GPII_FLOWMANAGER_PREFERENCES_URL
          value: http://preferences.default.svc.cluster.local/preferences/%userToken
        - name: GPII_FLOWMANAGER_LISTEN_PORT
          value: '8081'
