apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: preferences
spec:
  replicas: 6
  template:
    metadata:
      labels:
        app: preferences
    spec:
      containers:
      - name: preferences
        image: gpii/universal
        ports:
        - containerPort: 8081
        env:
        - name: NODE_ENV
          value: gpii.config.preferencesServer.standalone.production
        - name: GPII_PREFERENCES_DATASOURCE_URL
          value: http://couchdb.default.svc.cluster.local:5984/preferences/%userToken
        - name: GPII_PREFERENCES_LISTEN_PORT
          value: '8081'
